[package]
name = "simd-example"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"

[dev-dependencies.criterion]
version = "0.5.1"
features = ["html_reports"]

[[bench]]
name = "find"
harness = false
