[package]
name = "mpsc-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytes = "1.10.0"
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
