[package]
name = "value-log"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytes = "1.9.0"
crc32fast = "1.4.2"
fast-async-mutex = "0.6.7"
regex = "1.11.1"
rio = "0.9.4"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
