[package]
name = "rio-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
nix = "0.29.0"
rio = "0.9.4"
scopeguard = "1.2.0"
tempfile = "3.15.0"
tokio = { version = "1.43.0", features = ["full"] }
